# Generated by Django 5.0 on 2024-04-14 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='archived_profile_pics/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTimeRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ID', models.CharField(default='default_value', max_length=20, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listofstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNum', models.CharField(default='', max_length=10)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(default='1999-05-24')),
                ('age', models.PositiveIntegerField(default='')),
                ('status', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Permanent', 'Permanent')], default='', max_length=20)),
                ('position', models.CharField(choices=[('Instructor 1', 'Instructor 1'), ('Instructor 2', 'Instructor 2'), ('Instructor 3', 'Instructor 3')], default='', max_length=20)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10)),
                ('organization', models.CharField(choices=[('Chairperson,DCS', 'Chairperson,DCS'), ('Program Chair,CS', 'Program Chair,CS'), ('Program Chair, IT', 'Program Chair, IT'), ('Instructor', 'Instructor'), ('Head, LMS', 'Head, LMS'), ('Head, DCS RDE', 'Head, DCS RDE')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrgChartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('time_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employee')),
            ],
        ),
    ]
