# Generated by Django 5.0 on 2024-04-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_ID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
