# Generated by Django 5.0 on 2024-04-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_ID',
        ),
        migrations.RemoveField(
            model_name='listofstaff',
            name='idNum',
        ),
        migrations.AddField(
            model_name='listofstaff',
            name='employee_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.listofstaff'),
        ),
    ]
