# Generated by Django 5.0 on 2024-04-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_employee_employee_id_remove_listofstaff_idnum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerecord',
            old_name='time_employee',
            new_name='employee',
        ),
    ]
