# Generated by Django 5.0 on 2024-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_time_employee_timerecord_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofstaff',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
