# Generated by Django 5.0.3 on 2024-04-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_listofstaff_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofstaff',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='listofstaff',
            name='idNum',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
