# Generated by Django 5.0.3 on 2024-04-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_attendance_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='IdNum',
            field=models.CharField(default='', max_length=5),
        ),
    ]
