# Generated by Django 5.0.3 on 2024-04-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_attendance_idnum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listofstaff',
            new_name='Employee',
        ),
    ]
