# Generated by Django 5.0.3 on 2024-04-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_listofstaff_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedData',
        ),
        migrations.DeleteModel(
            name='DailyTimeRecords',
        ),
    ]
