# Generated by Django 5.0.3 on 2024-04-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
