# Generated by Django 5.0.3 on 2024-04-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_schedule_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.attendance'),
        ),
    ]
