# Generated by Django 5.0.3 on 2024-04-12 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_deletedrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_time_in', models.TimeField()),
                ('deleted_time_out', models.TimeField()),
                ('deleted_date', models.DateField()),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.attendance')),
            ],
        ),
        migrations.DeleteModel(
            name='DeletedRecord',
        ),
    ]
