# Generated by Django 5.0.3 on 2024-04-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_delete_attendancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('leave', 'Leave'), ('in', 'In'), ('out', 'Out')], default='in', max_length=20),
        ),
    ]
