# Generated by Django 5.0.3 on 2024-04-22 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdNum', models.CharField(default='', max_length=5)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('time_in', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time_out', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
