# Generated by Django 5.0.3 on 2024-04-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
