# Generated by Django 5.0.3 on 2024-04-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
