# Generated by Django 5.0.3 on 2024-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_history_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.CharField(max_length=50)),
                ('RmSched', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
            ],
        ),
    ]
