# Generated by Django 5.0.3 on 2024-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
