# Generated by Django 5.1 on 2024-11-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_userdata_address_userdata_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comlab',
            name='cards',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='comlab',
            name='comlab',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
