# Generated by Django 5.1 on 2024-11-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_equipment_remove_comlab_rmsched_remove_comlab_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
