# Generated by Django 5.1 on 2024-11-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_attendance_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgchartlist',
            name='orgName',
        ),
        migrations.AddField(
            model_name='orgchartlist',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orgchartlist',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
