# Generated by Django 5.1 on 2024-11-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_positiondcs_remove_orgchartlist_chairperson_dcs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positiondcs',
            old_name='Chairperson_DCS',
            new_name='positions',
        ),
        migrations.RemoveField(
            model_name='positiondcs',
            name='Instructors',
        ),
        migrations.RemoveField(
            model_name='positiondcs',
            name='Program_Chair_CS',
        ),
        migrations.RemoveField(
            model_name='positiondcs',
            name='Program_Chair_IT',
        ),
        migrations.RemoveField(
            model_name='orgchartlist',
            name='position_dcs',
        ),
        migrations.AddField(
            model_name='orgchartlist',
            name='position_dcs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.positiondcs'),
        ),
    ]
