# Generated by Django 5.1 on 2024-11-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_alter_equipment_date_alter_equipment_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='RmSched',
        ),
    ]
