# Generated by Django 5.1.4 on 2025-01-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_instructor_ins_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ins_schedule',
            name='instructor',
        ),
        migrations.AddField(
            model_name='ins_schedule',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.employee'),
            preserve_default=False,
        ),
    ]
